### ISSUE TITLE
Put on Stackage

### ISSUE THREAD

**Issue by barrucadu** [elliottt/hsirc#15]
It'd be nice to have this on Stackage, as I have a couple of IRC-related packages which use this for parsing messages, which have been requested to be stackaged.

The process looks pretty simple: https://github.com/fpco/stackage#get-your-package-included

If you don't have the time to maintain this any more, perhaps we could arrange something?

**Comment by bb010g** [comment]
:+1:

**Comment by elliottt** [comment]
I'm happy to keep maintaining it. I'll start the process of getting it on stackage :)

**Comment by elliottt** [comment]
https://github.com/fpco/stackage/pull/772

**Comment by bb010g** [comment]
[And it's been merged!](https://github.com/fpco/stackage/commit/f75005c4d951e72bc6df694a82467dc2d9df9f9a)

**Comment by barrucadu** [comment]
Awesome, thanks.
